version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: casdoor-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: casdoor
    ports:
      - "3306:3306"

  casdoor:
    image: casbin/casdoor
    container_name: casdoor
    depends_on:
      - mysql
    ports:
      - "8000:8000"
    environment:
      RUNNING_IN_DOCKER: "true"
      driverName: mysql
      dataSourceName: root:root@tcp(mysql:3306)/casdoor
